### ISSUE TITLE
[BUG] Chat in champion select is extremely slow

### ISSUE THREAD

**Issue by Peoples933** [hawolt/SwiftRift#213]
**Describe the bug**
After joining champion select and typing a message it appears in 1-2 seconds delay

**To Reproduce**
Account Region: eune
1. Start blind pick
2. Enter champion select
3. Try to type
4. Message appears with big delay

**Expected behavior**
The message should appear instantly like in the classic client

**Comment by hawolt** [comment]
what I think it might be:

- you have one outputstream from the socket
- for every action within the cs (hover/ban/pick/spell change) we send a presence on that one socket
- if we now send a message it has to send x amount of presences before our message is send creating a big delay

possible solution: if this is the actual cause a possible solution would be to only update presence when entering cs and when locking in champ during cs rather than all other events

I will take a look at this soon

**Comment by hawolt** [comment]
should be resolved on dev build - can be found on discord - please let me know
please keep in mind that instantly sending a message when you see the chat will still not show up instant as the message is displayed as soon as riot return it as swiftrift will make the chat useable way earlier than it actually would be available

**Comment by hawolt** [comment]
will be fixed next dev or main release
